version: '3.8'

services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8000}:8000"
    depends_on:
      - db
      - redis
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app:z

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Europe/Prague
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
